# Development environment values
replicaCount: 1

image:
  registry: public.ecr.aws
  registryAlias: "l5d5a3i0"
  repository: eks-fast-api
  pullPolicy: Always
  tag: "latest"

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
